spring.application.name=jwt-nimbus-demo
server.port=8005

# SQL Server
# Nếu bạn dùng default instance:
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jwt_nimbus_demo;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

# Nếu bạn dùng SQLEXPRESS thì dùng dòng dưới (comment dòng trên):
# spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=jwt_nimbus_demo;encrypt=true;trustServerCertificate=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT (Base64, tối thiểu 32 bytes sau khi decode)
security.jwt.secret-key=2uGmN4QmXgF9y3G1Q3B7Wc6mX2i9d0o0GgZc1wHnq1k=
security.jwt.expiration-time=3600000